// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMIQatei2TBUCHUK5SDjDCIdJbUNA-FIU',
    appId: '1:1049152511285:web:c2e7f4344195bb73c8407c',
    messagingSenderId: '1049152511285',
    projectId: 'colombia-words-and-expre-fdc82',
    authDomain: 'colombia-words-and-expre-fdc82.firebaseapp.com',
    storageBucket: 'colombia-words-and-expre-fdc82.firebasestorage.app',
    measurementId: 'G-6GHG8HEZ1N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6d7spqOJaheQXkTLO4Rsn_k9audpe1mU',
    appId: '1:1049152511285:android:f31cbd411e9cba4cc8407c',
    messagingSenderId: '1049152511285',
    projectId: 'colombia-words-and-expre-fdc82',
    storageBucket: 'colombia-words-and-expre-fdc82.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsUIujIS2cr0olfm0jWEvye-Nen6FaXpk',
    appId: '1:1049152511285:ios:61db846c44ba4b80c8407c',
    messagingSenderId: '1049152511285',
    projectId: 'colombia-words-and-expre-fdc82',
    storageBucket: 'colombia-words-and-expre-fdc82.firebasestorage.app',
    iosBundleId: 'com.example.colombiaWordsAndExpressions',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsUIujIS2cr0olfm0jWEvye-Nen6FaXpk',
    appId: '1:1049152511285:ios:61db846c44ba4b80c8407c',
    messagingSenderId: '1049152511285',
    projectId: 'colombia-words-and-expre-fdc82',
    storageBucket: 'colombia-words-and-expre-fdc82.firebasestorage.app',
    iosBundleId: 'com.example.colombiaWordsAndExpressions',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMIQatei2TBUCHUK5SDjDCIdJbUNA-FIU',
    appId: '1:1049152511285:web:ec196befb3a31e6ac8407c',
    messagingSenderId: '1049152511285',
    projectId: 'colombia-words-and-expre-fdc82',
    authDomain: 'colombia-words-and-expre-fdc82.firebaseapp.com',
    storageBucket: 'colombia-words-and-expre-fdc82.firebasestorage.app',
    measurementId: 'G-SXS6878LY5',
  );

}